---
- name: Deploy Kerberos Server to my-server
  hosts: all
  vars:
    realm_name: REAL.COMPANYNAME.COM
    kdc_port: 88
    master_db_pass: br34km3
    kadmin_user: kadmincompany
    kadmin_pass: k4dm1np4ss
  roles:
    - { role: AlberTajuelo.ansible-kerberos-server }